[build]
  base = "java"
  dir = "cpmatmed/backend"
  buildCommand = "./mvn clean package"

[phases.setup]
nixPkgs = ['jdk8', 'maven']

[phases.build]
cmds = ['cd backend && mvn clean install']

[start]
cmd = 'java -jar backend/target/backend-0.0.1-SNAPSHOT.jar'
