version: '3.8'

services:
  db:
    image: postgres:15
    container_name: cpmatmed-postgres
    restart: always
    environment:
      POSTGRES_DB: dbpmatmed
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d  # <-- se quiser executar SQL automaticamente

  pgadmin:
    image: dpage/pgadmin4
    container_name: cpmatmed-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres-data:
