spring:
  config:
    activate:
      on-profile: default
  application:
    name: ${SPRING_APPLICATION_NAME:cpmatmed-backend}

management:
  endpoint:
    health:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health

---
# Configurações carregadas apenas se nenhum perfil estiver ativo
spring:
  profiles: default
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/db_cpmatmed} # Valor padrão
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:senha}