spring:
  config:
    activate:
      on-profile: prod  # ✅ Sintaxe correta
  datasource:
    url: ${SPRING_DATASOURCE_URL}?sslmode=require
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 60000
      initialization-fail-timeout: 60000
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect  # Dialect versionado
        jdbc:
          time_zone: UTC
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: false
  mvc:
    cors:
      allowed-origins: https://app.cpmatmed.com.br
  sql:
    init:
      mode: never

server:
  port: 8080

management:
  endpoint:
    health:
      show-details: never
  endpoints:
    web:
      exposure:
        include: health