spring:
  config:
    activate:
      on-profile: test  
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: sa
    password: ''
    hikari:
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql
  flyway:
    enabled: false
  h2:
    console:
      enabled: true
      path: /h2-console
  mvc:
    cors:
      allowed-origins: '*'
  info:
    app:
      name: Cpmatmed
      description: Backend do sistema Cpmatmed
      version: 1.0.0