# Configurações GLOBAIS (sem perfil ativo)
spring:
  config:
    activate:
      on-profile: default  # Define que este bloco é para o perfil 'default'
  application:
    name: ${SPRING_APPLICATION_NAME:cpmatmed-backend}

management:
  endpoint:
    health:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health

---
# Configurações do perfil 'default' (quando o perfil está ativo)
spring:
  config:
    activate:
      on-profile: default
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/db_cpmatmed}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:CzvAukGtQLfJymGQpfKvERveaIuXnLMk}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: update
    show-sql: true