# Configurações GLOBAIS (sem perfil ativo)
spring:
  application:
    name: cpmatmed-backend
    
server:
  port: ${PORT:8080}  
---
# Perfil 'default' (ativo se nenhum outro perfil for especificado)
spring:
  config:
    activate:
      on-profile: default
  datasource:
    url:  jdbc:postgresql://turntable.proxy.rlwy.net:28497/railway
    username: postgres
    password: "CzvAukGtQLfJymGQpfKvERveaIuXnLMk"
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect  # Dialect específico
    hibernate:
      ddl-auto: update
    show-sql: true

---
# Configurações do Management (ativas em todos os perfis)
management:
  endpoint:
    health:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,metrics  # Lista explícita
  info:
    app:
      name: Cpmatmed
      description: Backend do sistema Cpmatmed
      version: 1.0.0