# Configurações GLOBAIS (sem perfil ativo)
spring:
  application:
    name: cpmatmed-backend
  datasource:
    url: jdbc:postgresql://turntable.proxy.rlwy.net:28497/railway
    username: postgres
    password: CzvAukGtQLfJymGQpfKvERveaIuXnLMk
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: ${PORT:8080}

logging.level.root: DEBUG
logging.level.org.springframework: DEBUG

---
# Configurações do Management (ativas em todos os perfis)
management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      enabled: true
      show-details: always
  info:
    app:
      name: Cpmatmed
      description: Backend do sistema Cpmatmed
      version: 1.0.0
