spring:
  config:
    activate:
      on-profile: default
  application:
    name: cpmatmed-backend
  profiles:
    active: default  # Força o perfil padrão

management:
  endpoint:
    health:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health

---
spring:
  profiles: default
  datasource:
    url: jdbc:postgresql://localhost:5432/db_cpmatmed
    username: postgres
    password: CzvAukGtQLfJymGQpfKvERveaIuXnLMk
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    org.hibernate: DEBUG
    org.springframework.jdbc: DEBUG