spring:
  config:
    activate:
      on-profile: default
  application:
    name: ${SPRING_APPLICATION_NAME:cpmatmed-backend}

management:
  endpoint:
    health:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health

---
# Configurações do perfil "default"
spring:
  profiles: default
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/db_cpmatmed}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:CzvAukGtQLfJymGQpfKvERveaIuXnLMk}  # Senha corrigida
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect  # Dialect correto
    hibernate:
      ddl-auto: update   # Comportamento do schema
    show-sql: true       # Exibe SQL no console (útil para desenvolvimento)