spring:
  config:
    activate:
      on-profile: dev  # ✅ Sintaxe correta para Spring Boot 2.4+
  datasource:
    url: jdbc:postgresql://localhost:5432/db_cpmatmed  # Corrigi o nome do banco (era "dbpmatmed")
    username: postgres
    password: SAMUEL
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect  # Dialect versionado
        format_sql: true
    open-in-view: false
  mvc:
    cors:
      allowed-origins: "*"