# Configurações GLOBAIS (aplicáveis a todos os perfis)
spring:
  application:
    name: cpmatmed-backend

---
# Configurações do perfil 'default' (ativação explícita)
spring:
  config:
    activate:
      on-profile: default  # Define que este bloco pertence ao perfil 'default'
  datasource:
    url: jdbc:postgresql://localhost:5432/db_cpmatmed
    username: postgres
    password: CzvAukGtQLfJymGQpfKvERveaIuXnLMk
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

---
# Configurações de Health Check (sem perfil específico)
management:
  endpoint:
    health:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health