spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:postgresql://${PostgreSQL.HOST}:${PostgreSQL.PORT}/${PostgreSQL.DATABASE}?sslmode=require
    username: ${PostgreSQL.USER}
    password: ${PostgreSQL.PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 60000
      initialization-fail-timeout: 60000

  jpa:
    hibernate:
      ddl-auto: validate  # Verifica se o schema está correto (não altera o banco!)
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        jdbc:
          time_zone: UTC

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: false

  mvc:
    cors:
      allowed-origins: https://app.cpmatmed.com.br

  sql:
    init:
      mode: never  # Não inicializa dados automaticamente em produção

server:
  port: 8080

management:
  endpoint:
    health:
      show-details: never
  endpoints:
    web:
      exposure:
        include: health
